# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22394436e80681f3a66340a4e7ea0c0c32ddd9a1b7b671d425f171f1ac01a8ff69f5e574d10c791a47929f0e68f227db97ce6f79cab9c2d11ec20f261572117b

test:
  secret_key_base: 102320f4b211db3eccf60e977009c2ea95c9f4f9a646e98117289cc9ca8355c3c63363815747a5f330e04b5c2681e8d02794decab933d50d24f67f5a03acabc8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
